"""Indian cinema + politics expansion. Merged into seed generation.

Does not change the engine or schema. Industries/states/roles become
likelihood overrides via existing questions.
"""

from __future__ import annotations

from typing import Any

from knowledge_expansion_v2 import E


def A(
    name: str,
    aliases: list[str],
    *industries: str,
    pop: int = 70,
    female: bool = False,
    alive: bool = True,
    extra_roles: tuple[str, ...] = (),
) -> dict[str, Any]:
    roles = ("actor",) + extra_roles
    return E(
        name,
        "Movies",
        aliases,
        pop=pop,
        real=True,
        alive=alive,
        female=female,
        regions=("india",),
        industries=industries,
        roles=roles,
    )


def D(
    name: str,
    aliases: list[str],
    *industries: str,
    pop: int = 68,
    female: bool = False,
    alive: bool = True,
) -> dict[str, Any]:
    return E(
        name,
        "Movies",
        aliases,
        pop=pop,
        real=True,
        alive=alive,
        female=female,
        regions=("india",),
        industries=industries,
        roles=("director",),
    )


def P(
    name: str,
    aliases: list[str],
    *states: str,
    pop: int = 70,
    female: bool = False,
    alive: bool = True,
    category: str = "Politicians",
    extra_roles: tuple[str, ...] = (),
) -> dict[str, Any]:
    roles = ("politician",) + extra_roles
    return E(
        name,
        category,
        aliases,
        pop=pop,
        real=True,
        alive=alive,
        female=female,
        regions=("india",),
        states=states,
        roles=roles,
    )


ENTRIES: list[dict[str, Any]] = [
    # —— Hindi / Bollywood actors (overlay + new) ——
    A("Amitabh Bachchan", ["Big B", "Amitabh"], "hindi", pop=96),
    A("Shah Rukh Khan", ["SRK", "King Khan", "Shahrukh Khan"], "hindi", pop=98),
    A("Salman Khan", ["Sallu", "Salman"], "hindi", pop=90),
    A("Aamir Khan", ["Aamir", "Mr Perfectionist"], "hindi", pop=90),
    A("Akshay Kumar", ["Akshay", "Khiladi Kumar"], "hindi", pop=86),
    A("Ajay Devgn", ["Ajay Devgan", "Ajay"], "hindi", pop=80),
    A("Hrithik Roshan", ["Hrithik"], "hindi", pop=84),
    A("Ranbir Kapoor", ["Ranbir"], "hindi", pop=82),
    A("Ranveer Singh", ["Ranveer"], "hindi", pop=82),
    A("Shahid Kapoor", ["Shahid"], "hindi", pop=72),
    A("Saif Ali Khan", ["Saif"], "hindi", pop=74),
    A("Anil Kapoor", ["Anil"], "hindi", pop=76),
    A("Sanjay Dutt", ["Sanjay", "Sanju Baba"], "hindi", pop=74),
    A("Suniel Shetty", ["Suniel", "Sunil Shetty"], "hindi", pop=62),
    A("Sidharth Malhotra", ["Sidharth"], "hindi", pop=66),
    A("Varun Dhawan", ["Varun"], "hindi", pop=70),
    A("Ayushmann Khurrana", ["Ayushmann"], "hindi", pop=72),
    A("Rajkummar Rao", ["Rajkumar Rao", "Rajkummar"], "hindi", pop=70),
    A("Pankaj Tripathi", ["Pankaj"], "hindi", pop=74),
    A("Nawazuddin Siddiqui", ["Nawazuddin", "Nawaz"], "hindi", pop=72),
    A("Manoj Bajpayee", ["Bajpayee"], "hindi", pop=72),
    A("Irrfan Khan", ["Irrfan"], "hindi", pop=80, alive=False),
    A("Paresh Rawal", ["Paresh"], "hindi", "gujarati", pop=68),
    A("Naseeruddin Shah", ["Naseeruddin"], "hindi", pop=74),
    A("Om Puri", ["Om Puri Actor"], "hindi", pop=70, alive=False),
    A("Rajesh Khanna", ["Kaka Khanna"], "hindi", pop=76, alive=False),
    A("Dharmendra", ["He-Man Dharmendra"], "hindi", "punjabi", pop=78),
    A("Shatrughan Sinha", ["Shatru", "Shotgun Sinha"], "hindi", extra_roles=("politician",), pop=64),
    A("Jeetendra", ["Jumping Jack Jeetendra"], "hindi", pop=62),
    A("Mithun Chakraborty", ["Mithun", "Disco Dancer"], "hindi", "bengali", extra_roles=("politician",), pop=70),
    A("Rishi Kapoor", ["Chintu Kapoor", "Rishi Kapoor Actor"], "hindi", pop=72, alive=False),
    A("Dev Anand", ["Dev Saab"], "hindi", pop=74, alive=False),
    A("Dilip Kumar", ["Tragedy King"], "hindi", pop=80, alive=False),
    A("Raj Kapoor", ["Showman Kapoor"], "hindi", extra_roles=("director",), pop=78, alive=False),
    A("Amit Sadh", ["Amit Sadh Actor"], "hindi", pop=52),
    A("Vicky Kaushal", ["Vicky Kaushal Actor"], "hindi", pop=74),
    A("Kartik Aaryan", ["Kartik Aaryan Actor"], "hindi", pop=70),
    A("Tiger Shroff", ["Tiger Shroff Actor"], "hindi", pop=68),
    A("John Abraham", ["John Abraham Actor"], "hindi", pop=70),
    A("Emraan Hashmi", ["Emraan"], "hindi", pop=62),
    A("Arjun Kapoor", ["Arjun Kapoor Actor"], "hindi", pop=58),
    A("Ishaan Khatter", ["Ishaan"], "hindi", pop=56),
    A("Farhan Akhtar", ["Farhan"], "hindi", extra_roles=("director",), pop=70),
    # Actresses Hindi
    A("Deepika Padukone", ["Deepika"], "hindi", pop=88, female=True),
    A("Alia Bhatt", ["Alia"], "hindi", pop=86, female=True),
    A("Priyanka Chopra", ["Priyanka", "PC Chopra"], "hindi", pop=88, female=True),
    A("Kareena Kapoor", ["Kareena", "Bebo"], "hindi", pop=82, female=True),
    A("Katrina Kaif", ["Katrina"], "hindi", pop=80, female=True),
    A("Anushka Sharma", ["Anushka"], "hindi", pop=76, female=True),
    A("Madhuri Dixit", ["Madhuri", "Dhak Dhak Girl"], "hindi", "marathi", pop=80, female=True),
    A("Sridevi", ["Sridevi Kapoor"], "hindi", "tamil", "telugu", pop=82, female=True, alive=False),
    A("Rekha", ["Rekha Actress"], "hindi", pop=78, female=True),
    A("Hema Malini", ["Dream Girl Hema"], "hindi", extra_roles=("politician",), pop=74, female=True),
    A("Kajol", ["Kajol Devgan"], "hindi", pop=76, female=True),
    A("Rani Mukerji", ["Rani Mukherjee"], "hindi", pop=74, female=True),
    A("Aishwarya Rai", ["Aishwarya", "Aishwarya Rai Bachchan"], "hindi", "tamil", pop=84, female=True),
    A("Vidya Balan", ["Vidya"], "hindi", pop=74, female=True),
    A("Taapsee Pannu", ["Taapsee"], "hindi", "punjabi", pop=68, female=True),
    A("Kangana Ranaut", ["Kangana"], "hindi", extra_roles=("politician",), pop=70, female=True),
    A("Kriti Sanon", ["Kriti"], "hindi", pop=70, female=True),
    A("Kiara Advani", ["Kiara"], "hindi", pop=68, female=True),
    A("Shraddha Kapoor", ["Shraddha"], "hindi", pop=72, female=True),
    A("Madhubala", ["Madhubala Actress"], "hindi", pop=76, female=True, alive=False),
    A("Meena Kumari", ["Tragedy Queen"], "hindi", pop=74, female=True, alive=False),
    A("Waheeda Rehman", ["Waheeda"], "hindi", pop=70, female=True),
    A("Janhvi Kapoor", ["Janhvi"], "hindi", pop=64, female=True),
    A("Sara Ali Khan", ["Sara Ali"], "hindi", pop=62, female=True),
    A("Disha Patani", ["Disha"], "hindi", pop=64, female=True),
    A("Nora Fatehi", ["Nora"], "hindi", pop=58, female=True),
    A("Bhumi Pednekar", ["Bhumi"], "hindi", pop=62, female=True),
    A("Parineeti Chopra", ["Parineeti"], "hindi", pop=64, female=True),
    A("Sonakshi Sinha", ["Sonakshi"], "hindi", pop=62, female=True),
    A("Jacqueline Fernandez", ["Jacqueline"], "hindi", pop=64, female=True),
    A("Tabu", ["Tabu Actress"], "hindi", pop=72, female=True),
    A("Juhi Chawla", ["Juhi"], "hindi", pop=66, female=True),
    A("Karisma Kapoor", ["Karisma"], "hindi", pop=66, female=True),
    A("Sushmita Sen", ["Sushmita"], "hindi", pop=64, female=True),
    A("Jaya Bachchan", ["Jaya Bhaduri"], "hindi", extra_roles=("politician",), pop=68, female=True),
    A("Govinda", ["Govinda Ahuja"], "hindi", extra_roles=("politician",), pop=70),
    A("Jackie Shroff", ["Jackie Shroff Actor"], "hindi", pop=66),
    A("Boman Irani", ["Boman"], "hindi", pop=64),
    A("Nargis", ["Nargis Dutt"], "hindi", pop=70, female=True, alive=False),
    A("Nutan", ["Nutan Actress"], "hindi", pop=66, female=True, alive=False),
    # —— Telugu ——
    A("Chiranjeevi", ["Megastar Chiranjeevi"], "telugu", extra_roles=("politician",), pop=86),
    A("Nagarjuna", ["King Nagarjuna", "ANR Jr"], "telugu", pop=76),
    A("Venkatesh", ["Victory Venkatesh"], "telugu", pop=72),
    A("Nandamuri Balakrishna", ["Balakrishna", "NBK"], "telugu", extra_roles=("politician",), pop=74),
    A("Mahesh Babu", ["Mahesh", "Superstar Mahesh"], "telugu", pop=84),
    A("Pawan Kalyan", ["Power Star Pawan"], "telugu", extra_roles=("politician",), pop=84),
    A("Allu Arjun", ["Stylish Star", "Allu", "AA Bunny"], "telugu", pop=88),
    A("Prabhas", ["Rebel Star", "Prabhas Raju", "Darling Prabhas"], "telugu", "hindi", pop=90),
    A("NTR Jr", ["Jr NTR", "Tarak", "Young Tiger NTR"], "telugu", pop=86),
    A("Ram Charan", ["Charan", "Mega Power Star"], "telugu", pop=84),
    A("Ravi Teja", ["Mass Maharaja"], "telugu", pop=72),
    A("Nani", ["Natural Star Nani"], "telugu", pop=74),
    A("Vijay Deverakonda", ["Deverakonda", "Rowdy Vijay"], "telugu", pop=74),
    A("Naga Chaitanya", ["Chay", "Naga Chaitanya Akkineni"], "telugu", pop=68),
    A("Dulquer Salmaan", ["Dulquer"], "malayalam", "tamil", "hindi", "telugu", pop=78),
    A("Naveen Polishetty", ["Polishetty"], "telugu", pop=64),
    A("Allu Sirish", ["Sirish"], "telugu", pop=52),
    A("Samantha Ruth Prabhu", ["Samantha"], "telugu", "tamil", pop=80, female=True),
    A("Anushka Shetty", ["Anushka Shetty Actress"], "telugu", "tamil", pop=76, female=True),
    A("Tamannaah Bhatia", ["Tamannaah", "Tamanna"], "telugu", "tamil", "hindi", pop=74, female=True),
    A("Rashmika Mandanna", ["Rashmika"], "telugu", "kannada", "hindi", pop=78, female=True),
    A("Kajal Aggarwal", ["Kajal"], "telugu", "tamil", "hindi", pop=70, female=True),
    A("Sai Pallavi", ["Sai Pallavi Actress"], "telugu", "tamil", "malayalam", pop=76, female=True),
    A("Keerthy Suresh", ["Keerthy"], "telugu", "tamil", pop=72, female=True),
    A("Pooja Hegde", ["Pooja Hegde Actress"], "telugu", "hindi", pop=68, female=True),
    A("Sreeleela", ["Sreeleela Actress"], "telugu", "kannada", pop=62, female=True),
    # —— Tamil ——
    A("Rajinikanth", ["Rajini", "Superstar Rajini", "Thalaivar"], "tamil", "hindi", pop=96),
    A("Kamal Haasan", ["Kamal Hassan", "Ulaganayagan"], "tamil", extra_roles=("politician",), pop=90),
    A("Vijay", ["Thalapathy Vijay", "Ilamai Thalapathy"], "tamil", pop=92),
    A("Ajith Kumar", ["Thala Ajith", "Ajith"], "tamil", pop=86),
    A("Suriya", ["Suriya Sivakumar"], "tamil", pop=80),
    A("Dhanush", ["Dhanush Rao"], "tamil", "hindi", pop=80),
    A("Vikram", ["Chiyaan Vikram"], "tamil", pop=78),
    A("Karthi", ["Karthi Sivakumar"], "tamil", pop=70),
    A("Vijay Sethupathi", ["Sethupathi", "Makkal Selvan"], "tamil", pop=76),
    A("Sivakarthikeyan", ["SK Sivakarthikeyan"], "tamil", pop=74),
    A("Vadivelu", ["Vadivelu Comedy"], "tamil", pop=72),
    A("Sathyaraj", ["Sathyaraj Actor"], "tamil", pop=64),
    A("Prakash Raj", ["Prakash Raj Actor"], "tamil", "telugu", "kannada", "hindi", pop=70),
    A("Sivaji Ganesan", ["Sivaji"], "tamil", pop=76, alive=False),
    A("M. G. Ramachandran", ["MGR", "Makkal Thilagam"], "tamil", extra_roles=("politician",), pop=82, alive=False),
    A("Jayalalithaa", ["Jaya Amma", "J Jayalalithaa"], "tamil", extra_roles=("politician",), pop=82, female=True, alive=False),
    A("Nayanthara", ["Lady Superstar", "Nayantara"], "tamil", "telugu", "malayalam", pop=84, female=True),
    A("Trisha Krishnan", ["Trisha"], "tamil", "telugu", pop=76, female=True),
    A("Jyothika", ["Jyothika Sadanah"], "tamil", pop=70, female=True),
    A("Shruti Haasan", ["Shruti Haasan Actress"], "tamil", "telugu", "hindi", pop=68, female=True),
    A("Simran", ["Simran Actress"], "tamil", "telugu", pop=62, female=True),
    A("Hansika Motwani", ["Hansika"], "tamil", "telugu", pop=56, female=True),
    # —— Malayalam ——
    A("Mammootty", ["Mammootty Actor", "Megastar Mammootty"], "malayalam", pop=90),
    A("Mohanlal", ["Lalettan", "Universal Star Mohanlal"], "malayalam", pop=90),
    A("Fahadh Faasil", ["Fahadh"], "malayalam", "tamil", pop=80),
    A("Prithviraj Sukumaran", ["Prithviraj"], "malayalam", "tamil", pop=76),
    A("Tovino Thomas", ["Tovino"], "malayalam", pop=70),
    A("Suresh Gopi", ["Suresh Gopi Actor"], "malayalam", extra_roles=("politician",), pop=68),
    A("Jayaram", ["Jayaram Actor"], "malayalam", "tamil", pop=64),
    A("Dileep", ["Dileep Actor"], "malayalam", pop=62),
    A("Nivin Pauly", ["Nivin"], "malayalam", pop=66),
    A("Kunchacko Boban", ["Kunchacko"], "malayalam", pop=62),
    A("Manju Warrier", ["Manju"], "malayalam", pop=72, female=True),
    A("Parvathy Thiruvothu", ["Parvathy"], "malayalam", "tamil", pop=70, female=True),
    A("Nazriya Nazim", ["Nazriya"], "malayalam", "tamil", pop=66, female=True),
    A("Nithya Menen", ["Nithya"], "malayalam", "tamil", "telugu", pop=70, female=True),
    A("Kavya Madhavan", ["Kavya"], "malayalam", pop=62, female=True),
    A("Shobana", ["Shobana Actress"], "malayalam", "tamil", pop=64, female=True),
    # —— Kannada ——
    A("Dr. Rajkumar", ["Rajkumar Kannada", "Annavru"], "kannada", pop=84, alive=False),
    A("Vishnuvardhan", ["Vishnuvardhan Kannada"], "kannada", pop=72, alive=False),
    A("Shiva Rajkumar", ["Shivanna"], "kannada", pop=70),
    A("Sudeep", ["Kichcha Sudeep"], "kannada", "hindi", pop=76),
    A("Darshan", ["Darshan Thoogudeepa", "Challenging Star"], "kannada", pop=72),
    A("Yash", ["Rocking Star Yash"], "kannada", "hindi", pop=86),
    A("Rakshit Shetty", ["Rakshit"], "kannada", pop=68),
    A("Rishab Shetty", ["Rishab"], "kannada", extra_roles=("director",), pop=74),
    A("Puneeth Rajkumar", ["Appu Puneeth", "Power Star Puneeth"], "kannada", pop=80, alive=False),
    A("Srinidhi Shetty", ["Srinidhi"], "kannada", "hindi", pop=62, female=True),
    A("Radhika Pandit", ["Radhika Pandit Actress"], "kannada", pop=58, female=True),
    # —— Bengali ——
    A("Soumitra Chatterjee", ["Soumitra"], "bengali", pop=76, alive=False),
    A("Uttam Kumar", ["Mahanayak Uttam"], "bengali", pop=78, alive=False),
    A("Prosenjit Chatterjee", ["Prosenjit", "Bumba"], "bengali", pop=72),
    A("Abir Chatterjee", ["Abir"], "bengali", pop=60),
    A("Jisshu Sengupta", ["Jisshu"], "bengali", pop=58),
    A("Aparna Sen", ["Aparna Sen Actress"], "bengali", extra_roles=("director",), pop=68, female=True),
    A("Rituparna Sengupta", ["Rituparna"], "bengali", pop=62, female=True),
    A("Dev Sahayam", ["Dev Bengali Actor"], "bengali", pop=58),
    # —— Marathi ——
    A("Nana Patekar", ["Nana"], "marathi", "hindi", pop=74),
    A("Makarand Anaspure", ["Anaspure"], "marathi", pop=56),
    A("Subodh Bhave", ["Subodh"], "marathi", pop=54),
    A("Sachin Khedekar", ["Khedekar"], "marathi", "hindi", pop=56),
    A("Swapnil Joshi", ["Swapnil"], "marathi", pop=58),
    A("Ashok Saraf", ["Ashok Saraf Actor"], "marathi", pop=64),
    A("Laxmikant Berde", ["Berde"], "marathi", pop=62, alive=False),
    A("Reema Lagoo", ["Reema"], "marathi", "hindi", pop=58, female=True, alive=False),
    A("Sai Tamhankar", ["Sai Tamhankar Actress"], "marathi", pop=56, female=True),
    A("Sonali Kulkarni", ["Sonali Kulkarni Actress"], "marathi", "hindi", pop=54, female=True),
    # —— Punjabi cinema ——
    A("Diljit Dosanjh", ["Diljit"], "punjabi", "hindi", pop=82),
    A("Gippy Grewal", ["Gippy"], "punjabi", pop=64),
    A("Ammy Virk", ["Ammy"], "punjabi", pop=60),
    A("Neeru Bajwa", ["Neeru"], "punjabi", pop=58, female=True),
    A("Sonam Bajwa", ["Sonam Bajwa Actress"], "punjabi", pop=56, female=True),
    A("Sargun Mehta", ["Sargun"], "punjabi", pop=58, female=True),
    A("Gurdas Maan", ["Gurdas"], "punjabi", pop=66),
    # —— Gujarati / Bhojpuri / Assamese / Odia ——
    A("Siddharth Randeria", ["Randeria"], "gujarati", pop=54),
    A("Malhar Thakar", ["Malhar"], "gujarati", pop=52),
    A("Kiran Kumar", ["Kiran Kumar Actor"], "hindi", "gujarati", pop=52),
    A("Dinesh Lal Yadav", ["Nirahua"], "bhojpuri", "hindi", pop=60),
    A("Khesari Lal Yadav", ["Khesari"], "bhojpuri", pop=58),
    A("Ravi Kishan", ["Ravi Kishan Actor"], "bhojpuri", "hindi", extra_roles=("politician",), pop=64),
    A("Pawan Singh", ["Pawan Singh Bhojpuri"], "bhojpuri", pop=56),
    A("Jaya Seal", ["Jaya Seal Actress"], "assamese", pop=48, female=True),
    A("Kopil Bora", ["Kopil"], "assamese", pop=48),
    A("Jatin Bora", ["Jatin Bora Actor"], "assamese", pop=50),
    A("Adil Hussain", ["Adil Hussain Actor"], "assamese", "hindi", pop=58),
    A("Anupam Kher", ["Anupam"], "hindi", pop=70),
    A("Babushan Mohanty", ["Babushan"], "odia", pop=50),
    A("Anubhav Mohanty", ["Anubhav Odia"], "odia", pop=54),
    A("Archita Sahu", ["Archita"], "odia", pop=48, female=True),
    # —— Directors ——
    D("Satyajit Ray", ["Ray Director", "Satyajit"], "bengali", "hindi", pop=86, alive=False),
    D("Rajkumar Hirani", ["Hirani", "Raju Hirani"], "hindi", pop=80),
    D("Sanjay Leela Bhansali", ["Bhansali", "SLB"], "hindi", pop=82),
    D("Karan Johar", ["KJo", "Dharma Karan"], "hindi", pop=78),
    D("Rohit Shetty", ["Rohit Shetty Director"], "hindi", pop=74),
    D("Yash Chopra", ["Yash Chopra Director"], "hindi", pop=78, alive=False),
    D("Aditya Chopra", ["Aditya Chopra Director"], "hindi", pop=70),
    D("Anurag Kashyap", ["Kashyap Director"], "hindi", pop=72),
    D("Zoya Akhtar", ["Zoya"], "hindi", pop=70, female=True),
    D("S. S. Rajamouli", ["Rajamouli", "SSR Director"], "telugu", "hindi", pop=90),
    D("Mani Ratnam", ["Mani Ratnam Director"], "tamil", "hindi", pop=82),
    D("S. Shankar", ["Shankar Director"], "tamil", pop=76),
    D("Lokesh Kanagaraj", ["Lokesh"], "tamil", pop=74),
    D("Gautham Vasudev Menon", ["Gautham Menon", "GVM"], "tamil", pop=68),
    D("Adoor Gopalakrishnan", ["Adoor"], "malayalam", pop=68, alive=True),
    D("Ritwik Ghatak", ["Ghatak"], "bengali", pop=64, alive=False),
    D("Mrinal Sen", ["Mrinal"], "bengali", pop=62, alive=False),
    D("Bimal Roy", ["Bimal Roy Director"], "hindi", "bengali", pop=66, alive=False),
    D("Guru Dutt", ["Guru Dutt Director"], "hindi", pop=74, alive=False),
    D("Mehboob Khan", ["Mehboob"], "hindi", pop=58, alive=False),
    D("Ram Gopal Varma", ["RGV"], "telugu", "hindi", pop=64),
    D("Sukumar", ["Sukumar Director"], "telugu", pop=70),
    D("Trivikram Srinivas", ["Trivikram"], "telugu", pop=70),
    D("Atlee", ["Atlee Kumar"], "tamil", "hindi", pop=68),
    D("Vetrimaaran", ["Vetrimaaran Director"], "tamil", pop=70),
    D("Mysskin", ["Mysskin Director"], "tamil", pop=58),
    D("Jeethu Joseph", ["Jeethu"], "malayalam", pop=64),
    D("Lijo Jose Pellissery", ["Lijo Jose"], "malayalam", pop=64),
    D("Nagraj Manjule", ["Manjule"], "marathi", "hindi", pop=62),
    # —— National politicians ——
    P("Narendra Modi", ["Modi", "Narendra"], "gujarat", pop=96),
    P("Jawaharlal Nehru", ["Nehru", "Pandit Nehru"], "uttar_pradesh", pop=90, alive=False),
    P("Sardar Vallabhbhai Patel", ["Sardar Patel", "Iron Man of India"], "gujarat", pop=86, alive=False),
    P("Indira Gandhi", ["Indira"], "uttar_pradesh", pop=88, female=True, alive=False),
    P("Rajiv Gandhi", ["Rajiv"], "uttar_pradesh", pop=80, alive=False),
    P("Atal Bihari Vajpayee", ["Vajpayee", "Atal"], "uttar_pradesh", pop=86, alive=False),
    P("Manmohan Singh", ["Manmohan"], "punjab", pop=84, alive=False),
    P("Lal Bahadur Shastri", ["Lal Bahadur", "LB Shastri"], "uttar_pradesh", pop=80, alive=False),
    P("Morarji Desai", ["Morarji"], "gujarat", pop=70, alive=False),
    P("P. V. Narasimha Rao", ["Narasimha Rao", "PV Narasimha Rao"], "andhra_pradesh", pop=78, alive=False),
    P("V. P. Singh", ["VP Singh", "Vishwanath Pratap Singh"], "uttar_pradesh", pop=66, alive=False),
    P("Charan Singh", ["Chaudhary Charan Singh"], "uttar_pradesh", pop=64, alive=False),
    P("Chandra Shekhar", ["Chandra Shekhar Prime Minister"], "uttar_pradesh", pop=60, alive=False),
    P("I. K. Gujral", ["IK Gujral", "Inder Kumar Gujral"], "punjab", pop=60, alive=False),
    P("Dr. Rajendra Prasad", ["Rajendra Prasad", "First President"], "bihar", pop=80, alive=False),
    P("Ram Nath Kovind", ["Kovind"], "uttar_pradesh", pop=70),
    P("Droupadi Murmu", ["Murmu", "Draupadi Murmu"], "jharkhand", pop=76, female=True),
    P("Pratibha Patil", ["Pratibha"], "maharashtra", pop=64, female=True),
    P("Pranab Mukherjee", ["Pranab"], "west_bengal", pop=74, alive=False),
    P("Zakir Husain", ["Zakir Hussain President"], "bihar", pop=62, alive=False),
    P("Sonia Gandhi", ["Sonia"], "uttar_pradesh", pop=78, female=True),
    P("Rahul Gandhi", ["Rahul Gandhi Politician"], "uttar_pradesh", pop=80),
    P("Amit Shah", ["Amit Shah Politician"], "gujarat", pop=84),
    P("Rajnath Singh", ["Rajnath"], "uttar_pradesh", pop=74),
    P("Nirmala Sitharaman", ["Sitharaman"], "tamil_nadu", pop=72, female=True),
    P("S. Jaishankar", ["Jaishankar"], "delhi", pop=70),
    # —— Freedom movement / historical ——
    P("Mahatma Gandhi", ["Gandhi", "Bapu", "Mohandas Gandhi"], "gujarat", pop=96, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Subhas Chandra Bose", ["Netaji", "Netaji Bose"], "west_bengal", pop=90, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Bhagat Singh", ["Bhagat", "Shaheed Bhagat Singh"], "punjab", pop=88, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Chandrashekhar Azad", ["Chandra Shekhar Azad", "Shaheed Azad"], "uttar_pradesh", pop=80, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Bal Gangadhar Tilak", ["Tilak", "Lokmanya Tilak"], "maharashtra", pop=80, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Lala Lajpat Rai", ["Lajpat Rai", "Punjab Kesari"], "punjab", pop=76, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Bipin Chandra Pal", ["Bipin Pal"], "west_bengal", pop=66, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Sarojini Naidu", ["Sarojini", "Nightingale Sarojini"], "uttar_pradesh", pop=78, female=True, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Annie Besant", ["Besant"], "tamil_nadu", pop=64, female=True, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Maulana Abul Kalam Azad", ["Maulana Azad", "Abul Kalam Azad"], "west_bengal", pop=76, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("B. R. Ambedkar", ["Ambedkar", "Babasaheb", "Dr. B. R. Ambedkar"], "maharashtra", pop=92, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Dadabhai Naoroji", ["Naoroji", "Grand Old Man"], "maharashtra", pop=70, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Gopal Krishna Gokhale", ["Gokhale"], "maharashtra", pop=70, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Vinayak Damodar Savarkar", ["Savarkar", "Veer Savarkar"], "maharashtra", pop=74, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Mangal Pandey", ["Mangal Pandey Freedom"], "uttar_pradesh", pop=68, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    P("Rani Lakshmibai", ["Rani of Jhansi", "Lakshmibai"], "uttar_pradesh", pop=82, female=True, alive=False, category="Historical Figures", extra_roles=("freedom_fighter",)),
    # —— State / regional leaders (significant, not invented) ——
    P("Yogi Adityanath", ["Yogi", "Adityanath"], "uttar_pradesh", pop=82),
    P("Akhilesh Yadav", ["Akhilesh"], "uttar_pradesh", pop=74),
    P("Mayawati", ["Kumari Mayawati", "Behenji"], "uttar_pradesh", pop=76, female=True),
    P("Mulayam Singh Yadav", ["Mulayam", "Netaji Mulayam"], "uttar_pradesh", pop=74, alive=False),
    P("Devendra Fadnavis", ["Fadnavis"], "maharashtra", pop=76),
    P("Uddhav Thackeray", ["Uddhav"], "maharashtra", pop=72),
    P("Sharad Pawar", ["Pawar"], "maharashtra", pop=78),
    P("Bal Thackeray", ["Balasaheb Thackeray", "Balasaheb"], "maharashtra", pop=74, alive=False),
    P("Eknath Shinde", ["Eknath"], "maharashtra", pop=66),
    P("Nitin Gadkari", ["Gadkari"], "maharashtra", pop=72),
    P("Mamata Banerjee", ["Didi Mamata", "Mamata"], "west_bengal", pop=84, female=True),
    P("Jyoti Basu", ["Jyoti Basu CM"], "west_bengal", pop=70, alive=False),
    P("Buddhadeb Bhattacharjee", ["Buddhadeb"], "west_bengal", pop=62, alive=False),
    P("Nitish Kumar", ["Nitish"], "bihar", pop=78),
    P("Lalu Prasad Yadav", ["Lalu", "Lalu Prasad"], "bihar", pop=76),
    P("Tejashwi Yadav", ["Tejashwi"], "bihar", pop=70),
    P("Ashok Gehlot", ["Gehlot"], "rajasthan", pop=68),
    P("Vasundhara Raje", ["Vasundhara"], "rajasthan", pop=64, female=True),
    P("Bhupendra Patel", ["Bhupendra Patel CM"], "gujarat", pop=58),
    P("Shivraj Singh Chouhan", ["Shivraj", "Mama Chouhan"], "madhya_pradesh", pop=72),
    P("Kamal Nath", ["Kamal Nath Politician"], "madhya_pradesh", pop=60),
    P("M. K. Stalin", ["Stalin MK", "MK Stalin"], "tamil_nadu", pop=78),
    P("M. Karunanidhi", ["Karunanidhi", "Kalaignar"], "tamil_nadu", pop=76, alive=False),
    P("Siddaramaiah", ["Siddaramaiah CM"], "karnataka", pop=70),
    P("B. S. Yediyurappa", ["Yediyurappa", "BSY"], "karnataka", pop=66),
    P("H. D. Deve Gowda", ["Deve Gowda"], "karnataka", pop=68),
    P("Pinarayi Vijayan", ["Pinarayi"], "kerala", pop=74),
    P("K. Karunakaran", ["Karunakaran"], "kerala", pop=60, alive=False),
    P("N. Chandrababu Naidu", ["Chandrababu Naidu", "CBN"], "andhra_pradesh", pop=78),
    P("Y. S. Jagan Mohan Reddy", ["Jagan", "YS Jagan"], "andhra_pradesh", pop=74),
    P("N. T. Rama Rao", ["Nandamuri Taraka Rama Rao", "NTR Senior"], "andhra_pradesh", extra_roles=("actor",), pop=82, alive=False),
    P("K. Chandrashekar Rao", ["KCR", "K Chandrashekar Rao"], "telangana", pop=74),
    P("Naveen Patnaik", ["Naveen Patnaik CM"], "odisha", pop=76),
    P("Biju Patnaik", ["Biju"], "odisha", pop=66, alive=False),
    P("Bhagwant Mann", ["Bhagwant"], "punjab", pop=68),
    P("Parkash Singh Badal", ["Badal"], "punjab", pop=66, alive=False),
    P("Amarinder Singh", ["Captain Amarinder"], "punjab", pop=64),
    P("Manohar Lal Khattar", ["Khattar"], "haryana", pop=62),
    P("Bhupinder Singh Hooda", ["Hooda"], "haryana", pop=60),
    P("Arvind Kejriwal", ["Kejriwal"], "delhi", pop=82),
    P("Sheila Dikshit", ["Sheila"], "delhi", pop=66, female=True, alive=False),
    P("Hemant Soren", ["Hemant Soren CM"], "jharkhand", pop=64),
    P("Raghubar Das", ["Raghubar"], "jharkhand", pop=54),
    P("Bhupesh Baghel", ["Baghel"], "chhattisgarh", pop=60),
    P("Raman Singh", ["Dr Raman Singh"], "chhattisgarh", pop=58),
    P("Himanta Biswa Sarma", ["Himanta"], "assam", pop=70),
    P("Tarun Gogoi", ["Gogoi"], "assam", pop=58, alive=False),
    P("Pushkar Singh Dhami", ["Dhami"], "uttarakhand", pop=56),
    P("Sukhvinder Singh Sukhu", ["Sukhu"], "himachal_pradesh", pop=54),
    P("Pramod Sawant", ["Sawant"], "goa", pop=54),
    P("Omar Abdullah", ["Omar Abdullah JK"], "jammu_kashmir", pop=66),
    P("Mehbooba Mufti", ["Mehbooba"], "jammu_kashmir", pop=64, female=True),
    P("Farooq Abdullah", ["Farooq"], "jammu_kashmir", pop=64),
    P("Asaduddin Owaisi", ["Owaisi"], "telangana", pop=66),
    P("Ghulam Nabi Azad", ["Ghulam Nabi"], "jammu_kashmir", pop=58),
    P("K. R. Narayanan", ["KR Narayanan"], "kerala", pop=68, alive=False),
    P("R. Venkataraman", ["Ramaswamy Venkataraman"], "tamil_nadu", pop=60, alive=False),
]

# Drop empty placeholders, then last-write-wins on the same canonical name.
ENTRIES = [e for e in ENTRIES if e.get("popularity", 0) > 0 and e.get("name") and e.get("aliases")]
_by_name: dict[str, dict[str, Any]] = {}
for _row in ENTRIES:
    _by_name[_row["name"].casefold().strip()] = _row
ENTRIES = list(_by_name.values())

# Abdul Kalam: keep Scientists; politician role is historical (former President), no state.
ENTRIES.append(
    E(
        "A. P. J. Abdul Kalam",
        "Scientists",
        ["Abdul Kalam", "APJ Abdul Kalam", "Missile Man"],
        pop=92,
        real=True,
        alive=False,
        regions=("india",),
        roles=("politician",),
    )
)
_by_name = {e["name"].casefold().strip(): e for e in ENTRIES}
ENTRIES = list(_by_name.values())


def india_characters() -> list[tuple[str, str, list[str]]]:
    return [(e["name"], e["category"], list(e["aliases"])) for e in ENTRIES]


def india_popularity() -> dict[str, int]:
    return {e["name"].casefold(): int(e["popularity"]) for e in ENTRIES}


def trait_table_from_india(trait_factory) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for e in ENTRIES:
        out[e["name"].casefold()] = trait_factory(
            real=e["real"],
            alive=e["alive"],
            female=e["female"],
            regions=e["regions"],
            sports=e.get("sports") or (),
            fictional_media=e.get("media") or (),
            industries=e.get("industries") or (),
            states=e.get("states") or (),
            roles=e.get("roles") or (),
        )
    return out
