"""Curated global character expansion (real people + major fiction).

Merged into seed generation. Does not change the engine or schema.
Traits default: real people are real/alive unless marked otherwise;
fictional entries must set real=False.
"""

from __future__ import annotations

from typing import Any


def E(
    name: str,
    category: str,
    aliases: list[str],
    *,
    pop: int = 55,
    real: bool | None = None,
    alive: bool | None = None,
    female: bool = False,
    regions: tuple[str, ...] = (),
    sports: tuple[str, ...] = (),
    media: tuple[str, ...] = (),
    industries: tuple[str, ...] = (),
    states: tuple[str, ...] = (),
    roles: tuple[str, ...] = (),
) -> dict[str, Any]:
    fiction_cats = {
        "Movies",
        "TV Shows",
        "Anime",
        "Cartoons",
        "Gaming",
        "Mythology",
    }
    if real is None:
        real = False if (media or category in fiction_cats) else True
    if alive is None:
        alive = True if real else True
    return {
        "name": name,
        "category": category,
        "aliases": aliases,
        "popularity": int(pop),
        "real": real,
        "alive": alive,
        "female": female,
        "regions": tuple(regions),
        "sports": tuple(sports),
        "media": tuple(media),
        "industries": tuple(industries),
        "states": tuple(states),
        "roles": tuple(roles),
    }


# High-quality named characters missing from (or under-specified in) Phase 1.
ENTRIES: list[dict[str, Any]] = [
    # —— India sports ——
    E("Virat Kohli", "Sports", ["Virat", "King Kohli"], pop=100, regions=("india",), sports=("cricket",), roles=("batter",)),
    E("MS Dhoni", "Sports", ["Dhoni", "Mahi", "Mahendra Singh Dhoni", "MSD"], pop=98, regions=("india",), sports=("cricket",), roles=("wicketkeeper", "batter")),
    E("Rohit Sharma", "Sports", ["Hitman Sharma", "Rohit"], pop=95, regions=("india",), sports=("cricket",), roles=("batter", "opener")),
    E("Yuvraj Singh", "Sports", ["Yuvraj"], pop=82, regions=("india",), sports=("cricket",), roles=("batter",)),
    E("Rahul Dravid", "Sports", ["Dravid", "The Wall"], pop=84, regions=("india",), sports=("cricket",), roles=("batter",)),
    E("Jasprit Bumrah", "Sports", ["Bumrah"], pop=86, regions=("india",), sports=("cricket",), roles=("bowler",)),
    E("Hardik Pandya", "Sports", ["Pandya"], pop=80, regions=("india",), sports=("cricket",)),
    E("Ravindra Jadeja", "Sports", ["Jadeja", "Sir Jadeja"], pop=81, regions=("india",), sports=("cricket",)),
    E("Kapil Dev", "Sports", ["Kapil"], pop=83, regions=("india",), sports=("cricket",), roles=("bowler", "batter")),
    E("Sunil Gavaskar", "Sports", ["Gavaskar", "Sunny Gavaskar"], pop=80, regions=("india",), sports=("cricket",), roles=("batter", "opener", "debut_pre_2000")),
    E("Virender Sehwag", "Sports", ["Sehwag"], pop=76, regions=("india",), sports=("cricket",), roles=("batter", "opener")),
    E("Sourav Ganguly", "Sports", ["Ganguly", "Dada Ganguly"], pop=78, regions=("india",), sports=("cricket",), roles=("batter", "opener")),
    E("Anil Kumble", "Sports", ["Kumble", "Jumbo Kumble"], pop=74, regions=("india",), sports=("cricket",), roles=("bowler",)),
    E("Harbhajan Singh", "Sports", ["Harbhajan", "Bhajji"], pop=70, regions=("india",), sports=("cricket",), roles=("bowler",)),
    E("Zaheer Khan", "Sports", ["Zaheer"], pop=68, regions=("india",), sports=("cricket",), roles=("bowler",)),
    E("Shubman Gill", "Sports", ["Shubman"], pop=72, regions=("india",), sports=("cricket",), roles=("batter", "opener")),
    E("Suryakumar Yadav", "Sports", ["SKY Yadav", "Suryakumar"], pop=74, regions=("india",), sports=("cricket",), roles=("batter",)),
    E("KL Rahul", "Sports", ["Kannaur Rahul"], pop=70, regions=("india",), sports=("cricket",), roles=("batter", "opener")),
    E("Rishabh Pant", "Sports", ["Pant"], pop=73, regions=("india",), sports=("cricket",), roles=("wicketkeeper", "batter")),
    E("Mohammed Shami", "Sports", ["Shami"], pop=69, regions=("india",), sports=("cricket",), roles=("bowler",)),
    E("Neeraj Chopra", "Sports", ["Neeraj"], pop=88, regions=("india",), sports=("athletics",)),
    E("P. V. Sindhu", "Sports", ["PV Sindhu", "Sindhu"], pop=87, female=True, regions=("india",), sports=("badminton",)),
    E("Saina Nehwal", "Sports", ["Saina"], pop=80, female=True, regions=("india",), sports=("badminton",)),
    E("Mary Kom", "Sports", ["MC Mary Kom", "Mangte Chungneijang"], pop=84, female=True, regions=("india",), sports=("boxing",)),
    E("Milkha Singh", "Sports", ["Flying Sikh", "Milkha"], pop=78, alive=False, regions=("india",), sports=("athletics",)),
    E("Major Dhyan Chand", "Sports", ["Dhyan Chand", "Hockey Wizard"], pop=76, alive=False, regions=("india",), sports=("hockey",)),
    E("Leander Paes", "Sports", ["Paes"], pop=72, regions=("india",), sports=("tennis",)),
    E("Mahesh Bhupathi", "Sports", ["Bhupathi"], pop=64, regions=("india",), sports=("tennis",)),
    E("Viswanathan Anand", "Sports", ["Anand", "Vishy Anand"], pop=80, regions=("india",), sports=("other",)),
    E("Abhinav Bindra", "Sports", ["Bindra"], pop=70, regions=("india",), sports=("other",)),
    E("Saina Nehwal Player", "Sports", ["Nehwal"], pop=0),  # skipped via empty pop later? NO don't add dups
]

# Remove the accidental duplicate placeholder if I left it - I'll not include Saina Nehwal Player.
ENTRIES = [e for e in ENTRIES if e["name"] != "Saina Nehwal Player"]

ENTRIES += [
    E("Jhulan Goswami", "Sports", ["Jhulan"], pop=68, female=True, regions=("india",), sports=("cricket",)),
    E("Deepti Sharma", "Sports", ["Deepti"], pop=64, female=True, regions=("india",), sports=("cricket",)),
    E("Shafali Verma", "Sports", ["Shafali"], pop=62, female=True, regions=("india",), sports=("cricket",)),
    E("Ravi Shastri", "Sports", ["Shastri"], pop=66, regions=("india",), sports=("cricket",)),
    E("VVS Laxman", "Sports", ["Laxman", "Very Very Special"], pop=70, regions=("india",), sports=("cricket",)),
    # —— International sports extras ——
    E("Neymar", "Sports", ["Neymar Jr", "Neymar da Silva"], pop=90, regions=("americas",), sports=("football",)),
    E("Kylian Mbappé", "Sports", ["Mbappe", "Kylian"], pop=91, regions=("europe",), sports=("football",)),
    E("Erling Haaland", "Sports", ["Haaland"], pop=86, regions=("europe",), sports=("football",)),
    E("Mohamed Salah", "Sports", ["Salah", "Mo Salah"], pop=84, regions=("africa", "europe"), sports=("football",)),
    E("Sadio Mané", "Sports", ["Mane", "Sadio"], pop=78, regions=("africa", "europe"), sports=("football",)),
    E("Didier Drogba", "Sports", ["Drogba"], pop=76, regions=("africa", "europe"), sports=("football",)),
    E("Samuel Eto'o", "Sports", ["Eto'o", "Eto o"], pop=74, regions=("africa", "europe"), sports=("football",)),
    E("George Weah", "Sports", ["Weah"], pop=70, regions=("africa",), sports=("football",)),
    E("Son Heung-min", "Sports", ["Heung-min Son", "Sonny Son"], pop=80, regions=("asia", "europe"), sports=("football",)),
    E("Harry Kane", "Sports", ["Kane Football"], pop=82, regions=("uk", "europe"), sports=("football",)),
    E("Luka Modrić", "Sports", ["Modric"], pop=83, regions=("europe",), sports=("football",)),
    E("Kevin De Bruyne", "Sports", ["De Bruyne", "KDB"], pop=82, regions=("europe",), sports=("football",)),
    E("Robert Lewandowski", "Sports", ["Lewandowski"], pop=84, regions=("europe",), sports=("football",)),
    E("Karim Benzema", "Sports", ["Benzema"], pop=80, regions=("europe",), sports=("football",)),
    E("Andrés Iniesta", "Sports", ["Iniesta"], pop=82, regions=("europe",), sports=("football",)),
    E("Xavi", "Sports", ["Xavi Hernandez", "Xavi Hernández"], pop=81, regions=("europe",), sports=("football",)),
    E("Iker Casillas", "Sports", ["Casillas"], pop=76, regions=("europe",), sports=("football",)),
    E("Manuel Neuer", "Sports", ["Neuer"], pop=78, regions=("europe",), sports=("football",)),
    E("Paolo Maldini", "Sports", ["Maldini"], pop=75, regions=("europe",), sports=("football",)),
    E("Franz Beckenbauer", "Sports", ["Beckenbauer", "Der Kaiser"], pop=74, alive=False, regions=("europe",), sports=("football",)),
    E("Johan Cruyff", "Sports", ["Cruyff"], pop=76, alive=False, regions=("europe",), sports=("football",)),
    E("George Best", "Sports", ["Best Footballer"], pop=70, alive=False, regions=("uk", "europe"), sports=("football",)),
    E("Wayne Rooney", "Sports", ["Rooney"], pop=77, regions=("uk", "europe"), sports=("football",)),
    E("Sunil Chhetri", "Sports", ["Chhetri"], pop=74, regions=("india",), sports=("football",)),
    E("Novak Djokovic", "Sports", ["Djokovic", "Nole"], pop=92, regions=("europe",), sports=("tennis",)),
    E("Venus Williams", "Sports", ["Venus"], pop=82, female=True, regions=("usa",), sports=("tennis",)),
    E("Steffi Graf", "Sports", ["Graf"], pop=78, female=True, regions=("europe",), sports=("tennis",)),
    E("Maria Sharapova", "Sports", ["Sharapova"], pop=76, female=True, regions=("europe",), sports=("tennis",)),
    E("Andy Murray", "Sports", ["Murray"], pop=78, regions=("uk", "europe"), sports=("tennis",)),
    E("Carlos Alcaraz", "Sports", ["Alcaraz"], pop=80, regions=("europe",), sports=("tennis",)),
    E("Iga Świątek", "Sports", ["Swiatek", "Iga Swiatek"], pop=79, female=True, regions=("europe",), sports=("tennis",)),
    E("Max Verstappen", "Sports", ["Verstappen", "Mad Max F1"], pop=86, regions=("europe",), sports=("racing",)),
    E("Michael Schumacher", "Sports", ["Schumacher", "Schumi"], pop=85, regions=("europe",), sports=("racing",)),
    E("Ayrton Senna", "Sports", ["Senna"], pop=80, alive=False, regions=("americas",), sports=("racing",)),
    E("Sebastian Vettel", "Sports", ["Vettel"], pop=74, regions=("europe",), sports=("racing",)),
    E("Charles Leclerc", "Sports", ["Leclerc"], pop=72, regions=("europe",), sports=("racing",)),
    E("Floyd Mayweather", "Sports", ["Mayweather", "Money Mayweather"], pop=84, regions=("usa",), sports=("boxing",)),
    E("Manny Pacquiao", "Sports", ["Pacquiao", "Pacman Boxer"], pop=83, regions=("asia",), sports=("boxing",)),
    E("Mike Tyson", "Sports", ["Iron Mike", "Tyson"], pop=88, regions=("usa",), sports=("boxing",)),
    E("Conor McGregor", "Sports", ["McGregor", "The Notorious"], pop=80, regions=("europe", "uk"), sports=("mma",)),
    E("Khabib Nurmagomedov", "Sports", ["Khabib", "Nurmagomedov"], pop=78, regions=("europe",), sports=("mma",)),
    E("Anderson Silva", "Sports", ["The Spider Silva"], pop=70, regions=("americas",), sports=("mma",)),
    E("John Cena", "Sports", ["Cena"], pop=82, regions=("usa",), sports=("wrestling",)),
    E("Dwayne Johnson Wrestler", "Sports", ["The Rock Wrestler"], pop=0),  # skip - Dwayne is movies
    E("The Undertaker", "Sports", ["Undertaker", "Mark Calaway"], pop=76, regions=("usa",), sports=("wrestling",)),
    E("Stone Cold Steve Austin", "Sports", ["Stone Cold", "Steve Austin"], pop=74, regions=("usa",), sports=("wrestling",)),
    E("Shawn Michaels", "Sports", ["HBK Michaels"], pop=68, regions=("usa",), sports=("wrestling",)),
    E("Brock Lesnar", "Sports", ["Lesnar"], pop=72, regions=("usa",), sports=("wrestling", "mma")),
    E("Usain Bolt", "Sports", ["Lightning Bolt", "Bolt"], pop=90, regions=("americas",), sports=("athletics",)),
    E("Carl Lewis", "Sports", ["Carl Lewis Sprinter"], pop=70, regions=("usa",), sports=("athletics",)),
    E("Michael Phelps", "Sports", ["Phelps"], pop=86, regions=("usa",), sports=("swimming",)),
    E("Katie Ledecky", "Sports", ["Ledecky"], pop=74, female=True, regions=("usa",), sports=("swimming",)),
    E("Simone Biles", "Sports", ["Biles"], pop=88, female=True, regions=("usa",), sports=("gymnastics",)),
    E("Nadia Comăneci", "Sports", ["Comaneci", "Nadia"], pop=78, female=True, regions=("europe",), sports=("gymnastics",)),
    E("Tiger Woods", "Sports", ["Woods", "Tiger"], pop=88, regions=("usa",), sports=("golf",)),
    E("Rory McIlroy", "Sports", ["McIlroy"], pop=74, regions=("uk", "europe"), sports=("golf",)),
    E("Wayne Gretzky", "Sports", ["Gretzky", "The Great One"], pop=84, regions=("americas",), sports=("hockey",)),
    E("Sidney Crosby", "Sports", ["Crosby"], pop=74, regions=("americas",), sports=("hockey",)),
    E("Babe Ruth", "Sports", ["Sultan of Swat", "Bambino"], pop=82, alive=False, regions=("usa",), sports=("baseball",)),
    E("Jackie Robinson", "Sports", ["Robinson Baseball"], pop=76, alive=False, regions=("usa",), sports=("baseball",)),
    E("Shohei Ohtani", "Sports", ["Ohtani", "Shotime"], pop=84, regions=("japan", "usa"), sports=("baseball",)),
    E("Tom Brady", "Sports", ["TB12", "Brady"], pop=86, regions=("usa",), sports=("other",)),
    E("Lin Dan", "Sports", ["Lin Dan Super"], pop=70, regions=("asia",), sports=("badminton",)),
    E("Viktor Axelsen", "Sports", ["Axelsen"], pop=66, regions=("europe",), sports=("badminton",)),
    E("Karch Kiraly", "Sports", ["Kiraly"], pop=58, regions=("usa",), sports=("volleyball",)),
    E("Marta Vieira da Silva", "Sports", ["Marta Football", "Queen Marta"], pop=76, female=True, regions=("americas",), sports=("football",)),
    E("Megan Rapinoe", "Sports", ["Rapinoe"], pop=70, female=True, regions=("usa",), sports=("football",)),
    E("Alex Morgan", "Sports", ["Morgan Soccer"], pop=68, female=True, regions=("usa",), sports=("football",)),
    E("Cathy Freeman", "Sports", ["Freeman"], pop=64, female=True, regions=("australia",), sports=("athletics",)),
    E("Donald Bradman", "Sports", ["Bradman", "The Don"], pop=80, alive=False, regions=("australia",), sports=("cricket",)),
    E("Ricky Ponting", "Sports", ["Ponting", "Punter"], pop=76, regions=("australia",), sports=("cricket",)),
    E("Steve Smith", "Sports", ["Steve Smith Cricket"], pop=74, regions=("australia",), sports=("cricket",)),
    E("Kane Williamson", "Sports", ["Williamson Cricket"], pop=72, regions=("australia",), sports=("cricket",)),
    E("Joe Root", "Sports", ["Joe Root Cricket"], pop=72, regions=("uk",), sports=("cricket",)),
    E("Ben Stokes", "Sports", ["Stokes"], pop=74, regions=("uk",), sports=("cricket",)),
    E("Babar Azam", "Sports", ["Babar"], pop=76, regions=("asia",), sports=("cricket",)),
    E("Wasim Akram", "Sports", ["Akram"], pop=74, regions=("asia",), sports=("cricket",)),
    E("Brian Lara", "Sports", ["Lara"], pop=75, regions=("americas",), sports=("cricket",)),
    E("Chris Gayle", "Sports", ["Gayle", "Universe Boss"], pop=72, regions=("americas",), sports=("cricket",)),
    E("AB de Villiers", "Sports", ["ABD", "de Villiers"], pop=78, regions=("africa",), sports=("cricket",)),
    E("Jacques Kallis", "Sports", ["Kallis"], pop=72, regions=("africa",), sports=("cricket",)),
    E("Hashim Amla", "Sports", ["Amla"], pop=64, regions=("africa",), sports=("cricket",)),
    # —— India movies (real) ——
    E("Shah Rukh Khan", "Movies", ["SRK", "King Khan", "Shahrukh Khan"], pop=98, real=True, regions=("india",)),
    E("Amitabh Bachchan", "Movies", ["Big B", "Amitabh"], pop=96, real=True, regions=("india",)),
    E("Aamir Khan", "Movies", ["Aamir", "Mr Perfectionist"], pop=90, real=True, regions=("india",)),
    E("Salman Khan", "Movies", ["Sallu", "Salman"], pop=90, real=True, regions=("india",)),
    E("Akshay Kumar", "Movies", ["Akshay", "Khiladi Kumar"], pop=86, real=True, regions=("india",)),
    E("Ajay Devgn", "Movies", ["Ajay Devgan", "Ajay"], pop=80, real=True, regions=("india",)),
    E("Ranbir Kapoor", "Movies", ["Ranbir"], pop=82, real=True, regions=("india",)),
    E("Ranveer Singh", "Movies", ["Ranveer"], pop=82, real=True, regions=("india",)),
    E("Hrithik Roshan", "Movies", ["Hrithik"], pop=84, real=True, regions=("india",)),
    E("Shahid Kapoor", "Movies", ["Shahid"], pop=72, real=True, regions=("india",)),
    E("Varun Dhawan", "Movies", ["Varun"], pop=70, real=True, regions=("india",)),
    E("Rajinikanth", "Movies", ["Rajini", "Superstar Rajini", "Thalaivar"], pop=94, real=True, regions=("india",)),
    E("Kamal Haasan", "Movies", ["Kamal Hassan", "Ulaganayagan"], pop=86, real=True, regions=("india",)),
    E("Allu Arjun", "Movies", ["Stylish Star", "Allu"], pop=84, real=True, regions=("india",)),
    E("Prabhas", "Movies", ["Rebel Star", "Prabhas Raju"], pop=86, real=True, regions=("india",)),
    E("Mahesh Babu", "Movies", ["Mahesh", "Superstar Mahesh"], pop=80, real=True, regions=("india",)),
    E("Yash", "Movies", ["Rocking Star Yash"], pop=78, real=True, regions=("india",)),
    E("Vijay", "Movies", ["Thalapathy Vijay", "Ilamai Thalapathy"], pop=88, real=True, regions=("india",)),
    E("Suriya", "Movies", ["Suriya Sivakumar"], pop=76, real=True, regions=("india",)),
    E("Dhanush", "Movies", ["Dhanush Rao"], pop=74, real=True, regions=("india",)),
    E("NTR Jr", "Movies", ["Jr NTR", "Tarak"], pop=80, real=True, regions=("india",)),
    E("Ram Charan", "Movies", ["Charan"], pop=78, real=True, regions=("india",)),
    E("Deepika Padukone", "Movies", ["Deepika"], pop=88, real=True, female=True, regions=("india",)),
    E("Alia Bhatt", "Movies", ["Alia"], pop=86, real=True, female=True, regions=("india",)),
    E("Priyanka Chopra", "Movies", ["Priyanka", "PC Chopra"], pop=88, real=True, female=True, regions=("india", "usa")),
    E("Kareena Kapoor", "Movies", ["Kareena", "Bebo"], pop=82, real=True, female=True, regions=("india",)),
    E("Katrina Kaif", "Movies", ["Katrina"], pop=80, real=True, female=True, regions=("india",)),
    E("Nayanthara", "Movies", ["Lady Superstar", "Nayantara"], pop=78, real=True, female=True, regions=("india",)),
    E("Aishwarya Rai", "Movies", ["Aishwarya", "Aishwarya Rai Bachchan"], pop=84, real=True, female=True, regions=("india",)),
    E("Madhuri Dixit", "Movies", ["Madhuri", "Dhak Dhak Girl"], pop=80, real=True, female=True, regions=("india",)),
    E("Kajol", "Movies", ["Kajol Devgan"], pop=76, real=True, female=True, regions=("india",)),
    E("Vidya Balan", "Movies", ["Vidya"], pop=74, real=True, female=True, regions=("india",)),
    E("Kangana Ranaut", "Movies", ["Kangana"], pop=70, real=True, female=True, regions=("india",)),
    E("Anushka Sharma", "Movies", ["Anushka"], pop=76, real=True, female=True, regions=("india",)),
    E("Samantha Ruth Prabhu", "Movies", ["Samantha"], pop=74, real=True, female=True, regions=("india",)),
    E("Rashmika Mandanna", "Movies", ["Rashmika"], pop=72, real=True, female=True, regions=("india",)),
    E("Sridevi", "Movies", ["Sridevi Kapoor"], pop=82, real=True, alive=False, female=True, regions=("india",)),
    E("Dilip Kumar", "Movies", ["Tragedy King"], pop=74, real=True, alive=False, regions=("india",)),
    E("Raj Kapoor", "Movies", ["Showman Kapoor"], pop=72, real=True, alive=False, regions=("india",)),
    E("Guru Dutt", "Movies", ["Guru Dutt Director"], pop=66, real=True, alive=False, regions=("india",)),
    E("Satyajit Ray", "Movies", ["Ray Director"], pop=74, real=True, alive=False, regions=("india",)),
    E("Mani Ratnam", "Movies", ["Mani Ratnam Director"], pop=70, real=True, regions=("india",)),
    E("S. S. Rajamouli", "Movies", ["Rajamouli", "SSR Director"], pop=80, real=True, regions=("india",)),
    # —— International movies (real) ——
    E("Tom Cruise", "Movies", ["Cruise"], pop=90, real=True, regions=("usa",)),
    E("Leonardo DiCaprio", "Movies", ["DiCaprio", "Leo DiCaprio"], pop=92, real=True, regions=("usa",)),
    E("Dwayne Johnson", "Movies", ["The Rock", "Dwayne"], pop=91, real=True, regions=("usa",)),
    E("Will Smith", "Movies", ["Fresh Prince", "Willard Smith"], pop=88, real=True, regions=("usa",)),
    E("Robert Downey Jr.", "Movies", ["RDJ", "Downey"], pop=92, real=True, regions=("usa",)),
    E("Chris Hemsworth", "Movies", ["Hemsworth"], pop=84, real=True, regions=("australia", "usa")),
    E("Chris Evans", "Movies", ["Evans Captain"], pop=84, real=True, regions=("usa",)),
    E("Chris Pratt", "Movies", ["Pratt"], pop=80, real=True, regions=("usa",)),
    E("Johnny Depp", "Movies", ["Depp"], pop=86, real=True, regions=("usa",)),
    E("Keanu Reeves", "Movies", ["Keanu", "Reeves"], pop=88, real=True, regions=("usa", "americas")),
    E("Jackie Chan", "Movies", ["Chan Kong-sang", "Jackie"], pop=90, real=True, regions=("asia",)),
    E("Bruce Lee", "Movies", ["Lee Jun-fan", "Little Dragon"], pop=90, real=True, alive=False, regions=("asia", "usa")),
    E("Arnold Schwarzenegger", "Movies", ["Arnold", "Schwarzenegger", "Arnie"], pop=88, real=True, regions=("europe", "usa")),
    E("Sylvester Stallone", "Movies", ["Stallone", "Sly Stallone"], pop=84, real=True, regions=("usa",)),
    E("Tom Hanks", "Movies", ["Hanks"], pop=88, real=True, regions=("usa",)),
    E("Brad Pitt", "Movies", ["Pitt"], pop=86, real=True, regions=("usa",)),
    E("Morgan Freeman", "Movies", ["Freeman Actor"], pop=82, real=True, regions=("usa",)),
    E("Denzel Washington", "Movies", ["Denzel"], pop=84, real=True, regions=("usa",)),
    E("Daniel Craig", "Movies", ["Craig Bond"], pop=80, real=True, regions=("uk",)),
    E("Hugh Jackman", "Movies", ["Jackman"], pop=82, real=True, regions=("australia",)),
    E("Ryan Reynolds", "Movies", ["Reynolds"], pop=84, real=True, regions=("americas", "usa")),
    E("Benedict Cumberbatch", "Movies", ["Cumberbatch"], pop=78, real=True, regions=("uk",)),
    E("Idris Elba", "Movies", ["Elba"], pop=76, real=True, regions=("uk", "africa")),
    E("Angelina Jolie", "Movies", ["Jolie"], pop=86, real=True, female=True, regions=("usa",)),
    E("Jennifer Lawrence", "Movies", ["J-Law", "Jennifer L"], pop=84, real=True, female=True, regions=("usa",)),
    E("Emma Watson", "Movies", ["Watson Actress"], pop=86, real=True, female=True, regions=("uk",)),
    E("Scarlett Johansson", "Movies", ["Scarlett", "Johansson"], pop=86, real=True, female=True, regions=("usa",)),
    E("Margot Robbie", "Movies", ["Robbie"], pop=84, real=True, female=True, regions=("australia",)),
    E("Natalie Portman", "Movies", ["Portman"], pop=82, real=True, female=True, regions=("usa", "europe")),
    E("Meryl Streep", "Movies", ["Streep"], pop=84, real=True, female=True, regions=("usa",)),
    E("Audrey Hepburn", "Movies", ["Hepburn"], pop=80, real=True, alive=False, female=True, regions=("europe", "uk")),
    E("Marilyn Monroe", "Movies", ["Monroe", "Norma Jeane"], pop=84, real=True, alive=False, female=True, regions=("usa",)),
    E("Meryl? skip", "Movies", [], pop=0),
    E("Steven Spielberg", "Movies", ["Spielberg"], pop=86, real=True, regions=("usa",)),
    E("Christopher Nolan", "Movies", ["Nolan"], pop=84, real=True, regions=("uk", "usa")),
    E("Martin Scorsese", "Movies", ["Scorsese"], pop=82, real=True, regions=("usa",)),
    E("Quentin Tarantino", "Movies", ["Tarantino"], pop=80, real=True, regions=("usa",)),
    E("Alfred Hitchcock", "Movies", ["Hitchcock"], pop=80, real=True, alive=False, regions=("uk", "usa")),
    E("Hayao Miyazaki", "Movies", ["Miyazaki"], pop=84, real=True, regions=("japan",)),
    E("Charlie Chaplin", "Movies", ["Chaplin", "The Tramp"], pop=82, real=True, alive=False, regions=("uk",)),
    # —— Superheroes / fiction (ensure aliases + traits) ——
    E("Spider-Man", "Movies", ["Spiderman", "Spider Man", "Peter Parker"], pop=97, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Iron Man", "Movies", ["Tony Stark Hero"], pop=96, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Batman", "Movies", ["Bruce Wayne", "The Dark Knight"], pop=97, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Superman", "Movies", ["Clark Kent", "Kal-El"], pop=94, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Wonder Woman", "Movies", ["Diana Prince"], pop=90, real=False, female=True, regions=("usa", "europe"), media=("movie", "superhero")),
    E("Hulk", "Movies", ["Bruce Banner", "The Incredible Hulk"], pop=88, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Thor", "Movies", ["Thor Odinson Hero", "God of Thunder Hero"], pop=88, real=False, regions=("europe", "usa"), media=("movie", "superhero")),
    E("Captain America", "Movies", ["Steve Rogers"], pop=90, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Black Panther", "Movies", ["T'Challa", "T Challa"], pop=88, real=False, regions=("africa", "usa"), media=("movie", "superhero")),
    E("Deadpool", "Movies", ["Wade Wilson"], pop=86, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Wolverine", "Movies", ["Logan Howlett", "James Howlett"], pop=86, real=False, regions=("americas", "usa"), media=("movie", "superhero")),
    E("The Flash", "Movies", ["Barry Allen"], pop=80, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Aquaman", "Movies", ["Arthur Curry"], pop=78, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Doctor Strange", "Movies", ["Stephen Strange"], pop=82, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Black Widow", "Movies", ["Natasha Romanoff"], pop=82, real=False, female=True, regions=("europe", "usa"), media=("movie", "superhero")),
    E("Joker", "Movies", ["The Joker Villain", "Clown Prince"], pop=86, real=False, regions=("usa",), media=("movie", "superhero")),
    E("Harry Potter", "Movies", ["The Boy Who Lived", "Potter"], pop=98, real=False, regions=("uk",), media=("movie", "book")),
    E("Hermione Granger", "Movies", ["Hermione", "Granger"], pop=90, real=False, female=True, regions=("uk",), media=("movie", "book")),
    E("Ron Weasley", "Movies", ["Ron", "Weasley"], pop=84, real=False, regions=("uk",), media=("movie", "book")),
    E("Frodo Baggins", "Movies", ["Frodo", "Ring-bearer"], pop=86, real=False, regions=("uk", "europe"), media=("movie", "book")),
    E("Gandalf", "Movies", ["Gandalf the Grey", "Mithrandir"], pop=88, real=False, regions=("europe",), media=("movie", "book")),
    E("Sherlock Holmes", "Movies", ["Holmes", "Detective Holmes"], pop=90, real=False, regions=("uk",), media=("movie", "book")),
    # —— Cartoons extras ——
    E("Tom Cat", "Cartoons", ["Tom", "Thomas Cat"], pop=90, real=False, media=("cartoon",)),
    E("Jerry Mouse", "Cartoons", ["Jerry", "Jerry the Mouse"], pop=90, real=False, media=("cartoon",)),
    E("Mickey Mouse", "Cartoons", ["Mickey"], pop=94, real=False, regions=("usa",), media=("cartoon",)),
    E("Donald Duck", "Cartoons", ["Donald"], pop=86, real=False, regions=("usa",), media=("cartoon",)),
    E("Bugs Bunny", "Cartoons", ["Bugs"], pop=88, real=False, regions=("usa",), media=("cartoon",)),
    E("Scooby-Doo", "Cartoons", ["Scooby", "Scooby Doo"], pop=86, real=False, regions=("usa",), media=("cartoon",)),
    E("SpongeBob SquarePants", "Cartoons", ["SpongeBob", "Sponge"], pop=92, real=False, regions=("usa",), media=("cartoon",)),
    E("Ben Tennyson", "Cartoons", ["Ben 10", "Ben Ten"], pop=82, real=False, regions=("usa",), media=("cartoon",)),
    E("Popeye", "Cartoons", ["Popeye the Sailor"], pop=78, real=False, regions=("usa",), media=("cartoon",)),
    E("Doraemon", "Cartoons", ["Doramon"], pop=94, real=False, regions=("japan",), media=("cartoon",)),
    E("Shinchan", "Cartoons", ["Shin Chan", "Crayon Shin-chan", "Shinnosuke"], pop=93, real=False, regions=("japan",), media=("cartoon",)),
    E("Nobita Nobi", "Cartoons", ["Nobita"], pop=80, real=False, regions=("japan",), media=("cartoon",)),
    # —— Anime extras ——
    E("Naruto Uzumaki", "Anime", ["Naruto", "Seventh Hokage"], pop=96, real=False, regions=("japan",), media=("anime",)),
    E("Sasuke Uchiha", "Anime", ["Sasuke"], pop=88, real=False, regions=("japan",), media=("anime",)),
    E("Sakura Haruno", "Anime", ["Sakura"], pop=80, real=False, female=True, regions=("japan",), media=("anime",)),
    E("Kakashi Hatake", "Anime", ["Kakashi", "Copy Ninja"], pop=84, real=False, regions=("japan",), media=("anime",)),
    E("Goku", "Anime", ["Son Goku", "Kakarot"], pop=95, real=False, regions=("japan",), media=("anime",)),
    E("Vegeta", "Anime", ["Prince Vegeta"], pop=90, real=False, regions=("japan",), media=("anime",)),
    E("Monkey D. Luffy", "Anime", ["Luffy", "Straw Hat"], pop=94, real=False, regions=("japan",), media=("anime",)),
    E("Roronoa Zoro", "Anime", ["Zoro", "Pirate Hunter Zoro"], pop=88, real=False, regions=("japan",), media=("anime",)),
    E("Nami", "Anime", ["Nami Navigator"], pop=78, real=False, female=True, regions=("japan",), media=("anime",)),
    E("Tanjiro Kamado", "Anime", ["Tanjiro"], pop=86, real=False, regions=("japan",), media=("anime",)),
    E("Nezuko Kamado", "Anime", ["Nezuko"], pop=84, real=False, female=True, regions=("japan",), media=("anime",)),
    E("Satoru Gojo", "Anime", ["Gojo", "Gojo Satoru"], pop=88, real=False, regions=("japan",), media=("anime",)),
    E("Yuji Itadori", "Anime", ["Itadori"], pop=80, real=False, regions=("japan",), media=("anime",)),
    E("Eren Yeager", "Anime", ["Eren", "Attack Titan"], pop=86, real=False, regions=("japan",), media=("anime",)),
    E("Levi Ackerman", "Anime", ["Levi", "Captain Levi"], pop=88, real=False, regions=("japan",), media=("anime",)),
    E("Mikasa Ackerman", "Anime", ["Mikasa"], pop=82, real=False, female=True, regions=("japan",), media=("anime",)),
    E("Izuku Midoriya", "Anime", ["Deku", "Deku Midoriya"], pop=84, real=False, regions=("japan",), media=("anime",)),
    E("All Might", "Anime", ["Toshinori Yagi"], pop=78, real=False, regions=("japan",), media=("anime",)),
    E("Ash Ketchum", "Anime", ["Satoshi", "Ash"], pop=88, real=False, regions=("japan",), media=("anime",)),
    E("Pikachu", "Anime", ["Pika"], pop=94, real=False, regions=("japan",), media=("anime", "game")),
    E("Light Yagami", "Anime", ["Kira", "Light"], pop=84, real=False, regions=("japan",), media=("anime",)),
    E("Saitama", "Anime", ["Caped Baldy", "One Punch Man"], pop=86, real=False, regions=("japan",), media=("anime",)),
    E("Edward Elric", "Anime", ["Fullmetal", "Ed Elric"], pop=82, real=False, regions=("japan",), media=("anime",)),
    # —— Gaming ——
    E("Mario", "Gaming", ["Super Mario", "Mario Mario"], pop=96, real=False, regions=("europe", "usa"), media=("game",)),
    E("Luigi", "Gaming", ["Luigi Mario"], pop=84, real=False, regions=("europe", "usa"), media=("game",)),
    E("Link", "Gaming", ["Hero of Time"], pop=88, real=False, regions=("europe",), media=("game",)),
    E("Princess Zelda", "Gaming", ["Zelda"], pop=80, real=False, female=True, regions=("europe",), media=("game",)),
    E("Sonic the Hedgehog", "Gaming", ["Sonic"], pop=92, real=False, regions=("japan",), media=("game",)),
    E("Kratos", "Gaming", ["Ghost of Sparta"], pop=86, real=False, regions=("europe",), media=("game",)),
    E("Master Chief", "Gaming", ["John-117", "Chief"], pop=84, real=False, regions=("usa",), media=("game",)),
    E("Lara Croft", "Gaming", ["Croft", "Tomb Raider"], pop=84, real=False, female=True, regions=("uk",), media=("game",)),
    E("Steve", "Gaming", ["Minecraft Steve"], pop=86, real=False, media=("game",)),
    E("Creeper", "Gaming", ["Minecraft Creeper"], pop=82, real=False, media=("game",)),
    E("Pac-Man", "Gaming", ["Pacman"], pop=84, real=False, regions=("japan",), media=("game",)),
    E("Kirby", "Gaming", ["Kirby Pink"], pop=78, real=False, regions=("japan",), media=("game",)),
    E("Donkey Kong", "Gaming", ["DK Kong"], pop=76, real=False, regions=("usa",), media=("game",)),
    E("Pikachu Game", "Gaming", ["Pikachu Pocket"], pop=0),  # skip duplicate of anime Pikachu
    E("Jonesy", "Gaming", ["Fortnite Jonesy"], pop=70, real=False, regions=("usa",), media=("game",)),
    E("Trevor Philips", "Gaming", ["Trevor GTA"], pop=72, real=False, regions=("usa",), media=("game",)),
    E("Franklin Clinton", "Gaming", ["Franklin GTA"], pop=70, real=False, regions=("usa",), media=("game",)),
    E("Michael De Santa", "Gaming", ["Michael GTA"], pop=70, real=False, regions=("usa",), media=("game",)),
    E("Shigeru Miyamoto", "Gaming", ["Miyamoto Creator"], pop=78, real=True, regions=("japan",)),
    E("Hideo Kojima", "Gaming", ["Kojima"], pop=74, real=True, regions=("japan",)),
    E("Markus Persson", "Gaming", ["Notch"], pop=70, real=True, regions=("europe",)),
    E("Lee Sang-hyeok", "Gaming", ["Faker", "Unkillable Demon King"], pop=76, real=True, regions=("asia",)),
    # —— India politics / history / science / music / business ——
    E("Narendra Modi", "Politicians", ["Modi", "Narendra"], pop=94, regions=("india",)),
    E("Jawaharlal Nehru", "Politicians", ["Nehru", "Pandit Nehru"], pop=86, alive=False, regions=("india",)),
    E("Mahatma Gandhi", "Historical Figures", ["Gandhi", "Bapu", "Mohandas Gandhi"], pop=95, alive=False, regions=("india",)),
    E("Sardar Vallabhbhai Patel", "Politicians", ["Sardar Patel", "Iron Man of India"], pop=82, alive=False, regions=("india",)),
    E("Subhas Chandra Bose", "Historical Figures", ["Netaji", "Netaji Bose"], pop=86, alive=False, regions=("india",)),
    E("Indira Gandhi", "Politicians", ["Indira"], pop=84, alive=False, female=True, regions=("india",)),
    E("Atal Bihari Vajpayee", "Politicians", ["Vajpayee", "Atal"], pop=80, alive=False, regions=("india",)),
    E("B. R. Ambedkar", "Historical Figures", ["Ambedkar", "Babasaheb", "Dr. B. R. Ambedkar"], pop=88, alive=False, regions=("india",)),
    E("A. P. J. Abdul Kalam", "Scientists", ["Abdul Kalam", "APJ Abdul Kalam", "Missile Man"], pop=92, alive=False, regions=("india",)),
    E("Bhagat Singh", "Historical Figures", ["Bhagat", "Shaheed Bhagat Singh"], pop=86, alive=False, regions=("india",)),
    E("Chandragupta Maurya", "Historical Figures", ["Chandragupta"], pop=74, alive=False, regions=("india",)),
    E("Ashoka", "Historical Figures", ["Ashoka the Great", "Emperor Ashoka"], pop=82, alive=False, regions=("india",)),
    E("Akbar", "Historical Figures", ["Akbar the Great", "Jalal-ud-din Akbar"], pop=80, alive=False, regions=("india",)),
    E("Rani Lakshmibai", "Historical Figures", ["Rani of Jhansi", "Lakshmibai"], pop=82, alive=False, female=True, regions=("india",)),
    E("Shivaji Maharaj", "Historical Figures", ["Shivaji", "Chhatrapati Shivaji"], pop=86, alive=False, regions=("india",)),
    E("Maharana Pratap", "Historical Figures", ["Rana Pratap", "Pratap"], pop=80, alive=False, regions=("india",)),
    E("Tipu Sultan", "Historical Figures", ["Tipu", "Tiger of Mysore"], pop=72, alive=False, regions=("india",)),
    E("Rani Padmini", "Historical Figures", ["Padmini"], pop=64, alive=False, female=True, regions=("india",)),
    E("C. V. Raman", "Scientists", ["CV Raman", "Chandrasekhara Venkata Raman"], pop=82, alive=False, regions=("india",)),
    E("Homi J. Bhabha", "Scientists", ["Homi Bhabha", "Bhabha"], pop=76, alive=False, regions=("india",)),
    E("Vikram Sarabhai", "Scientists", ["Sarabhai"], pop=76, alive=False, regions=("india",)),
    E("Srinivasa Ramanujan", "Scientists", ["Ramanujan"], pop=86, alive=False, regions=("india", "uk")),
    E("Jagadish Chandra Bose", "Scientists", ["J. C. Bose", "JC Bose"], pop=74, alive=False, regions=("india",)),
    E("Satyendra Nath Bose", "Scientists", ["S. N. Bose", "Boson Bose"], pop=72, alive=False, regions=("india",)),
    E("Arijit Singh", "Musicians", ["Arijit"], pop=88, regions=("india",)),
    E("Lata Mangeshkar", "Musicians", ["Lata", "Nightingale of India"], pop=90, alive=False, female=True, regions=("india",)),
    E("Kishore Kumar", "Musicians", ["Kishore"], pop=86, alive=False, regions=("india",)),
    E("Asha Bhosle", "Musicians", ["Asha"], pop=82, female=True, regions=("india",)),
    E("Sonu Nigam", "Musicians", ["Sonu"], pop=76, regions=("india",)),
    E("Shreya Ghoshal", "Musicians", ["Shreya"], pop=80, female=True, regions=("india",)),
    E("A. R. Rahman", "Musicians", ["AR Rahman", "Rahman", "Mozart of Madras"], pop=90, regions=("india",)),
    E("Diljit Dosanjh", "Musicians", ["Diljit"], pop=80, regions=("india",)),
    E("Badshah", "Musicians", ["Aditya Prateek Singh Sisodia"], pop=74, regions=("india",)),
    E("Yo Yo Honey Singh", "Musicians", ["Honey Singh", "Yo Yo"], pop=74, regions=("india",)),
    E("Mohammed Rafi", "Musicians", ["Rafi"], pop=82, alive=False, regions=("india",)),
    E("Mukesh", "Musicians", ["Mukesh Singer"], pop=70, alive=False, regions=("india",)),
    E("Ilaiyaraaja", "Musicians", ["Ilaiyaraja", "Raja Maestro"], pop=78, regions=("india",)),
    E("Ratan Tata", "Business Leaders", ["Ratan", "Tata"], pop=90, alive=False, regions=("india",)),
    E("Mukesh Ambani", "Business Leaders", ["Ambani"], pop=86, regions=("india",)),
    E("Gautam Adani", "Business Leaders", ["Adani"], pop=80, regions=("india",)),
    E("N. R. Narayana Murthy", "Business Leaders", ["Narayana Murthy", "NRN"], pop=82, regions=("india",)),
    E("Azim Premji", "Business Leaders", ["Premji"], pop=78, regions=("india",)),
    E("Shiv Nadar", "Business Leaders", ["Nadar"], pop=74, regions=("india",)),
    E("Kumar Mangalam Birla", "Business Leaders", ["KM Birla", "Birla"], pop=70, regions=("india",)),
    E("Falguni Nayar", "Business Leaders", ["Nykaa Nayar"], pop=66, female=True, regions=("india",)),
    E("Byju Raveendran", "Business Leaders", ["Byju"], pop=60, regions=("india",)),
    # —— World politics ——
    E("Barack Obama", "Politicians", ["Obama", "Barack"], pop=92, regions=("usa",)),
    E("Donald Trump", "Politicians", ["Trump"], pop=90, regions=("usa",)),
    E("Joe Biden", "Politicians", ["Biden"], pop=84, regions=("usa",)),
    E("Abraham Lincoln", "Politicians", ["Lincoln", "Honest Abe"], pop=90, alive=False, regions=("usa",)),
    E("George Washington", "Politicians", ["Washington", "First President"], pop=88, alive=False, regions=("usa",)),
    E("Winston Churchill", "Politicians", ["Churchill"], pop=88, alive=False, regions=("uk", "europe")),
    E("Nelson Mandela", "Historical Figures", ["Mandela", "Madiba"], pop=92, alive=False, regions=("africa",)),
    E("Vladimir Putin", "Politicians", ["Putin"], pop=86, regions=("europe",)),
    E("Xi Jinping", "Politicians", ["Xi", "Jinping"], pop=84, regions=("asia",)),
    E("Volodymyr Zelenskyy", "Politicians", ["Zelensky", "Zelenskyy"], pop=84, regions=("europe",)),
    E("Margaret Thatcher", "Politicians", ["Thatcher", "Iron Lady"], pop=80, alive=False, female=True, regions=("uk",)),
    E("Queen Elizabeth II", "Historical Figures", ["Elizabeth II", "Queen Elizabeth"], pop=90, alive=False, female=True, regions=("uk",)),
    E("King Charles III", "Politicians", ["Charles III", "Prince Charles"], pop=76, regions=("uk",)),
    E("Jacinda Ardern", "Politicians", ["Ardern"], pop=74, female=True, regions=("australia",)),
    E("Justin Trudeau", "Politicians", ["Trudeau"], pop=76, regions=("americas",)),
    E("Emmanuel Macron", "Politicians", ["Macron"], pop=74, regions=("europe",)),
    E("Angela Merkel", "Politicians", ["Merkel"], pop=80, female=True, regions=("europe",)),
    E("Franklin D. Roosevelt", "Politicians", ["FDR", "Roosevelt"], pop=80, alive=False, regions=("usa",)),
    E("John F. Kennedy", "Politicians", ["JFK", "Kennedy"], pop=84, alive=False, regions=("usa",)),
    E("Theodore Roosevelt", "Politicians", ["Teddy Roosevelt"], pop=74, alive=False, regions=("usa",)),
    E("Golda Meir", "Politicians", ["Meir"], pop=68, alive=False, female=True, regions=("asia",)),
    E("Recep Tayyip Erdoğan", "Politicians", ["Erdogan", "Erdoğan"], pop=72, regions=("asia", "europe")),
    E("Imran Khan", "Politicians", ["Imran Khan Politician"], pop=78, regions=("asia",)),
    E("Sheikh Hasina", "Politicians", ["Hasina"], pop=70, female=True, regions=("asia",)),
    E("Mahinda Rajapaksa", "Politicians", ["Rajapaksa"], pop=58, regions=("asia",)),
    E("Cyril Ramaphosa", "Politicians", ["Ramaphosa"], pop=64, regions=("africa",)),
    E("Uhuru Kenyatta", "Politicians", ["Kenyatta"], pop=60, regions=("africa",)),
    E("Kwame Nkrumah", "Politicians", ["Nkrumah"], pop=66, alive=False, regions=("africa",)),
    E("Patrice Lumumba", "Historical Figures", ["Lumumba"], pop=64, alive=False, regions=("africa",)),
    E("Haile Selassie", "Historical Figures", ["Selassie"], pop=66, alive=False, regions=("africa",)),
    E("Gamal Abdel Nasser", "Politicians", ["Nasser"], pop=68, alive=False, regions=("africa", "asia")),
    E("Anwar Sadat", "Politicians", ["Sadat"], pop=64, alive=False, regions=("africa",)),
    E("Yasser Arafat", "Politicians", ["Arafat"], pop=66, alive=False, regions=("asia",)),
    E("King Hussein", "Politicians", ["Hussein of Jordan"], pop=58, alive=False, regions=("asia",)),
    E("Mohammed bin Salman", "Politicians", ["MBS", "Crown Prince MBS"], pop=72, regions=("asia",)),
    E("Reza Pahlavi", "Politicians", ["Shah of Iran"], pop=56, regions=("asia",)),
    E("Ayatollah Khomeini", "Historical Figures", ["Khomeini"], pop=64, alive=False, regions=("asia",)),
    E("Simón Bolívar", "Historical Figures", ["Bolivar", "El Libertador"], pop=74, alive=False, regions=("americas",)),
    E("Eva Perón", "Historical Figures", ["Evita", "Evita Peron"], pop=72, alive=False, female=True, regions=("americas",)),
    E("Fidel Castro", "Politicians", ["Castro"], pop=74, alive=False, regions=("americas",)),
    E("Che Guevara", "Historical Figures", ["Che", "Guevara"], pop=78, alive=False, regions=("americas",)),
    E("Lula da Silva", "Politicians", ["Lula", "Luiz Inácio Lula da Silva"], pop=74, regions=("americas",)),
    E("Jair Bolsonaro", "Politicians", ["Bolsonaro"], pop=68, regions=("americas",)),
    E("Andrés Manuel López Obrador", "Politicians", ["AMLO", "Lopez Obrador"], pop=64, regions=("americas",)),
    # —— Science / history extras ——
    E("Albert Einstein", "Scientists", ["Einstein"], pop=95, alive=False, regions=("europe", "usa")),
    E("Isaac Newton", "Scientists", ["Newton", "Sir Isaac Newton"], pop=92, alive=False, regions=("uk", "europe")),
    E("Nikola Tesla", "Scientists", ["Tesla"], pop=90, alive=False, regions=("europe", "usa")),
    E("Marie Curie", "Scientists", ["Madame Curie", "Curie"], pop=90, alive=False, female=True, regions=("europe",)),
    E("Charles Darwin", "Scientists", ["Darwin"], pop=88, alive=False, regions=("uk",)),
    E("Galileo Galilei", "Scientists", ["Galileo"], pop=86, alive=False, regions=("europe",)),
    E("Stephen Hawking", "Scientists", ["Hawking"], pop=88, alive=False, regions=("uk",)),
    E("Alan Turing", "Scientists", ["Turing"], pop=86, alive=False, regions=("uk",)),
    E("Thomas Edison", "Scientists", ["Edison"], pop=84, alive=False, regions=("usa",)),
    E("Leonardo da Vinci", "Historical Figures", ["da Vinci", "Leonardo"], pop=90, alive=False, regions=("europe",)),
    E("Ada Lovelace", "Scientists", ["Lovelace"], pop=80, alive=False, female=True, regions=("uk",)),
    E("Katherine Johnson", "Scientists", ["Katherine Goble"], pop=76, alive=False, female=True, regions=("usa",)),
    E("Neil Armstrong", "Scientists", ["Armstrong"], pop=84, alive=False, regions=("usa",)),
    E("Yuri Gagarin", "Scientists", ["Gagarin"], pop=78, alive=False, regions=("europe",)),
    E("Kalpana Chawla", "Scientists", ["Chawla"], pop=78, alive=False, female=True, regions=("india", "usa")),
    E("Rakesh Sharma", "Scientists", ["Rakesh Cosmonaut"], pop=70, regions=("india",)),
    E("Sunita Williams", "Scientists", ["Sunita"], pop=74, female=True, regions=("india", "usa")),
    E("James Watson", "Scientists", ["Watson DNA"], pop=64, alive=False, regions=("usa",)),
    E("Rosalind Franklin", "Scientists", ["Franklin DNA"], pop=76, alive=False, female=True, regions=("uk",)),
    E("Gregor Mendel", "Scientists", ["Mendel"], pop=72, alive=False, regions=("europe",)),
    E("Louis Pasteur", "Scientists", ["Pasteur"], pop=76, alive=False, regions=("europe",)),
    E("Alexander Fleming", "Scientists", ["Fleming"], pop=72, alive=False, regions=("uk",)),
    E("Dmitri Mendeleev", "Scientists", ["Mendeleev"], pop=70, alive=False, regions=("europe",)),
    E("Max Planck", "Scientists", ["Planck"], pop=70, alive=False, regions=("europe",)),
    E("Niels Bohr", "Scientists", ["Bohr"], pop=72, alive=False, regions=("europe",)),
    E("Richard Feynman", "Scientists", ["Feynman"], pop=76, alive=False, regions=("usa",)),
    E("Carl Sagan", "Scientists", ["Sagan"], pop=74, alive=False, regions=("usa",)),
    E("Jane Goodall", "Scientists", ["Goodall"], pop=76, female=True, regions=("uk", "africa")),
    E("Tim Berners-Lee", "Scientists", ["Berners-Lee", "Tim BL"], pop=78, regions=("uk",)),
    E("Grace Hopper", "Scientists", ["Hopper Admiral"], pop=72, alive=False, female=True, regions=("usa",)),
    E("Julius Caesar", "Historical Figures", ["Caesar"], pop=88, alive=False, regions=("europe",)),
    E("Alexander the Great", "Historical Figures", ["Alexander III"], pop=88, alive=False, regions=("europe", "asia")),
    E("Cleopatra", "Historical Figures", ["Cleopatra VII"], pop=88, alive=False, female=True, regions=("africa",)),
    E("Napoleon Bonaparte", "Historical Figures", ["Napoleon", "Bonaparte"], pop=90, alive=False, regions=("europe",)),
    E("Genghis Khan", "Historical Figures", ["Temujin", "Temüjin"], pop=86, alive=False, regions=("asia",)),
    E("Joan of Arc", "Historical Figures", ["Jeanne d'Arc", "Joan"], pop=84, alive=False, female=True, regions=("europe",)),
    E("Queen Elizabeth I", "Historical Figures", ["Elizabeth I", "Virgin Queen"], pop=82, alive=False, female=True, regions=("uk",)),
    E("Martin Luther King Jr.", "Historical Figures", ["MLK", "Martin Luther King"], pop=92, alive=False, regions=("usa",)),
    E("Harriet Tubman", "Historical Figures", ["Tubman"], pop=78, alive=False, female=True, regions=("usa",)),
    E("Rosa Parks", "Historical Figures", ["Parks"], pop=80, alive=False, female=True, regions=("usa",)),
    E("Malcolm X", "Historical Figures", ["Malcolm Little"], pop=78, alive=False, regions=("usa",)),
    E("William Shakespeare", "Literature", ["Shakespeare", "The Bard"], pop=90, alive=False, real=True, regions=("uk",)),
    E("Homer", "Literature", ["Homer Poet"], pop=74, alive=False, real=True, regions=("europe",)),
    E("Jane Austen", "Literature", ["Austen"], pop=82, alive=False, female=True, real=True, regions=("uk",)),
    E("Charles Dickens", "Literature", ["Dickens"], pop=80, alive=False, real=True, regions=("uk",)),
    E("Leo Tolstoy", "Literature", ["Tolstoy"], pop=78, alive=False, real=True, regions=("europe",)),
    E("Mark Twain", "Literature", ["Twain", "Samuel Clemens"], pop=80, alive=False, real=True, regions=("usa",)),
    E("J. K. Rowling", "Literature", ["JK Rowling", "Rowling"], pop=86, female=True, real=True, regions=("uk",)),
    E("J. R. R. Tolkien", "Literature", ["Tolkien", "JRR Tolkien"], pop=84, alive=False, real=True, regions=("uk",)),
    E("George Orwell", "Literature", ["Orwell", "Eric Blair"], pop=80, alive=False, real=True, regions=("uk",)),
    E("Maya Angelou", "Literature", ["Angelou"], pop=76, alive=False, female=True, real=True, regions=("usa",)),
    E("Rabindranath Tagore", "Literature", ["Tagore", "Gurudev"], pop=84, alive=False, real=True, regions=("india",)),
    E("Rumi", "Literature", ["Jalaluddin Rumi"], pop=76, alive=False, real=True, regions=("asia",)),
    E("Chinua Achebe", "Literature", ["Achebe"], pop=70, alive=False, real=True, regions=("africa",)),
    E("Wole Soyinka", "Literature", ["Soyinka"], pop=66, real=True, regions=("africa",)),
    E("Gabriel García Márquez", "Literature", ["Garcia Marquez", "Gabo"], pop=76, alive=False, real=True, regions=("americas",)),
    E("Pablo Neruda", "Literature", ["Neruda"], pop=72, alive=False, real=True, regions=("americas",)),
    E("Elon Musk", "Business Leaders", ["Musk", "Elon"], pop=90, regions=("africa", "usa")),
    E("Jeff Bezos", "Business Leaders", ["Bezos"], pop=86, regions=("usa",)),
    E("Bill Gates", "Business Leaders", ["Gates"], pop=88, regions=("usa",)),
    E("Steve Jobs", "Business Leaders", ["Jobs"], pop=90, alive=False, regions=("usa",)),
    E("Warren Buffett", "Business Leaders", ["Buffett", "Oracle of Omaha"], pop=84, regions=("usa",)),
    E("Mark Zuckerberg", "Business Leaders", ["Zuckerberg", "Zuck"], pop=84, regions=("usa",)),
    E("Sundar Pichai", "Business Leaders", ["Pichai", "Sundar"], pop=82, regions=("india", "usa")),
    E("Satya Nadella", "Business Leaders", ["Nadella", "Satya"], pop=80, regions=("india", "usa")),
    E("Tim Cook", "Business Leaders", ["Cook Apple"], pop=76, regions=("usa",)),
    E("Jack Ma", "Business Leaders", ["Ma Yun"], pop=76, regions=("asia",)),
    E("Oprah Winfrey", "Business Leaders", ["Oprah"], pop=86, female=True, regions=("usa",)),
    E("Beyoncé", "Musicians", ["Beyonce", "Queen Bey"], pop=92, female=True, regions=("usa",)),
    E("Taylor Swift", "Musicians", ["Swift", "Tay"], pop=94, female=True, regions=("usa",)),
    E("Michael Jackson", "Musicians", ["King of Pop", "MJ Jackson"], pop=94, alive=False, regions=("usa",)),
    E("Elvis Presley", "Musicians", ["Elvis", "The King"], pop=88, alive=False, regions=("usa",)),
    E("The Beatles", "Musicians", ["Beatles", "Fab Four"], pop=92, regions=("uk",)),
    E("Freddie Mercury", "Musicians", ["Mercury", "Freddie"], pop=88, alive=False, regions=("uk", "africa")),
    E("Eminem", "Musicians", ["Slim Shady", "Marshall Mathers"], pop=88, regions=("usa",)),
    E("Drake", "Musicians", ["Aubrey Graham", "Drizzy"], pop=86, regions=("americas", "usa")),
    E("Rihanna", "Musicians", ["RiRi", "Rihanna Fenty"], pop=86, female=True, regions=("americas",)),
    E("Adele", "Musicians", ["Adele Adkins"], pop=84, female=True, regions=("uk",)),
    E("Ed Sheeran", "Musicians", ["Sheeran"], pop=82, regions=("uk",)),
    E("BTS", "Musicians", ["Bangtan", "Bangtan Sonyeondan"], pop=88, regions=("asia",)),
    E("Blackpink", "Musicians", ["BLACKPINK"], pop=84, female=True, regions=("asia",)),
    E("PSY", "Musicians", ["Gangnam Style", "Park Jae-sang"], pop=74, regions=("asia",)),
    E("Bob Marley", "Musicians", ["Marley"], pop=84, alive=False, regions=("americas",)),
    E("Madonna", "Musicians", ["Madonna Ciccone"], pop=84, female=True, regions=("usa",)),
    E("Whitney Houston", "Musicians", ["Whitney"], pop=82, alive=False, female=True, regions=("usa",)),
    E("Aretha Franklin", "Musicians", ["Queen of Soul"], pop=80, alive=False, female=True, regions=("usa",)),
    E("Mozart", "Musicians", ["Wolfgang Amadeus Mozart", "Amadeus"], pop=86, alive=False, regions=("europe",)),
    E("Beethoven", "Musicians", ["Ludwig van Beethoven"], pop=86, alive=False, regions=("europe",)),
    E("Oprah Host", "TV Shows", ["Oprah TV"], pop=0),  # skip
]

# Drop zero-pop placeholders and accidental empties.
ENTRIES = [
    e
    for e in ENTRIES
    if e.get("popularity", 0) > 0 and e.get("name") and e.get("aliases")
]


def expansion_characters() -> list[tuple[str, str, list[str]]]:
    return [(e["name"], e["category"], list(e["aliases"])) for e in ENTRIES]


def expansion_popularity() -> dict[str, int]:
    return {e["name"].casefold(): int(e["popularity"]) for e in ENTRIES}


def trait_table_from_expansion(trait_factory) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for e in ENTRIES:
        out[e["name"].casefold()] = trait_factory(
            real=e["real"],
            alive=e["alive"],
            female=e["female"],
            regions=e["regions"],
            sports=e["sports"],
            fictional_media=e["media"],
            industries=e.get("industries") or (),
            states=e.get("states") or (),
            roles=e.get("roles") or (),
        )
    return out
